### ISSUE TITLE
PassThroughManager removed from django-model-utils in version 2.4 on 2015-12-03

### ISSUE THREAD

**Issue by crdunwel** [openpolis/django-popolo#22]
See change log at

https://github.com/carljm/django-model-utils/blob/master/CHANGES.rst#24-2015-12-03

And relevant commit

https://github.com/carljm/django-model-utils/commit/2824ec2e4875ab6530caa440034959d51d5b9830

This affects models using PassThroughManager in https://github.com/openpolis/django-popolo/blob/master/popolo/models.py . Discussion on the commit suggests as of Django 1.7 that  `QuerySet.as_manager()` achieves the same result.

**Comment by guglielmo** [comment]
PassThroughManager usage is trapped and substituted with direct call to QuerySet.as_manager().
The import of GenericTabularInline is made compatible with django v.1.6 and previous in the admin.py definitions.
